### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by aljawaid** [Tagirijus/DashboardTaskSorting#1]
Your readme mentions a MIT license, but it is not include din the repository.... did you delete it by accident from the template?

Does this retain the user settings or is it just adding options in the dropdown?

The screenshot is not clear on what is being shown.

**Comment by Tagirijus** [comment]
Hey there, thanks for your feedback and the hint. I just added the license - to be honest: I used your Kanboard plugin skeleton README.md afterwards and forgot the license ... woops!

Regarding the second question: this plugin simply changes the default sorting. I tried to make it a bit more clear in the README now. Though: I even extended the default sorting to be like `1. sort by due date ASC, while keeping tasks without any due date at the bottom` plus `2. then sort by priority DESC`. Hm, maybe I should add this  also to the README!

Screenshot: I find it rather hard to have a screenshot at all for something which just changes the internal default sorting logic. :D
